# 这是用户自定义的翻译，节名为语言
# 当与默认翻译文件有相同键名时，优先使用本文件的翻译，如ecco_menu_exit

[schinese]
Weapon="武器"
Item="物品"
357Revolver="357左轮手枪"
9mmAR="9mm突击步枪"
9mmHandgun="9mm手枪"
Crossbow="十字弩"
Crowbar="撬棍"
Displacer="位移炮"
DesertEagle="沙漠之鹰"
Egon="伊贡粒子枪"
Gauss="高斯枪"
Glock="格洛克手枪"
Grapple="抓钩枪"
HandGrenade="手雷"
HornetGun="黄蜂枪"
M16="M16步枪"
M249="M249机枪"
Medkit="医疗包"
Minigun="加特林机枪"
MP5="MP5冲锋枪"
PipeWrench="管钳"
RPG="RPG火箭筒"
Satchel="遥控炸弹"
ShockRifle="电击步枪"
Shotgun="霰弹枪"
Snark="小黄鸭"
SniperRifle="狙击步枪"
SporeLauncher="孢子发射器"
Tripmine="激光地雷"
Uzi="乌兹冲锋枪"
HealthKit="急救包"
Battery="电池"

[english]
Weapon="Weapons"
Item="Items"
357Revolver="357 Revolver"
9mmAR="9mm Assault Rifle"
9mmHandgun="9mm Handgun"
Crossbow="Crossbow"
Crowbar="Crowbar"
Displacer="Displacer"
DesertEagle="Desert Eagle"
Egon="Egon Gun"
Gauss="Gauss Gun"
Glock="Glock"
Grapple="Grapple"
HandGrenade="Hand Grenade"
HornetGun="Hornet Gun"
M16="M16 Rifle"
M249="M249 Machine Gun"
Medkit="Medkit"
Minigun="Minigun"
MP5="MP5"
PipeWrench="Pipe Wrench"
RPG="RPG Launcher"
Satchel="Satchel Charge"
ShockRifle="Shock Rifle"
Shotgun="Shotgun"
Snark="Snark"
SniperRifle="Sniper Rifle"
SporeLauncher="Spore Launcher"
Tripmine="Tripmine"
Uzi="Uzi"
HealthKit="Health Kit"
Battery="Battery"

[spanish]
Weapon="Armas"
Item="Objetos"
357Revolver="Revólver 357"
9mmAR="Rifle de Asalto 9mm"
9mmHandgun="Pistola 9mm"
Crossbow="Ballesta"
Crowbar="Palanca"
Displacer="Desplazador"
DesertEagle="Águila del Desierto"
Egon="Pistola de Partículas Egon"
Gauss="Pistola Gauss"
Glock="Glock"
Grapple="Gancho"
HandGrenade="Granada"
HornetGun="Pistola de Avispas"
M16="Rifle M16"
M249="Ametralladora M249"
Medkit="Botiquín"
Minigun="Minigun"
MP5="MP5"
PipeWrench="Llave de Tubería"
RPG="Lanzacohetes RPG"
Satchel="Carga Explosiva"
ShockRifle="Rifle de Choque"
Shotgun="Escopeta"
Snark="Snark"
SniperRifle="Rifle de Francotirador"
SporeLauncher="Lanzador de Esporas"
Tripmine="Mina Láser"
Uzi="Uzi"
HealthKit="Botiquín Médico"
Battery="Batería"